name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your ideas for improving Sunona.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like.
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: This feature would help me...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category does this feature belong to?
      options:
        - New STT Provider
        - New TTS Provider
        - New LLM Provider
        - New Telephony Provider
        - AI Agents
        - Knowledge Base
        - Billing
        - API/Server
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've thought about?

  - type: dropdown
    id: contribute
    attributes:
      label: Are you willing to contribute this feature?
      options:
        - Yes, I can implement this
        - I can help with testing
        - I can help with documentation
        - No, I'm just suggesting

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, examples, or references?
